#!/bin/bash
#SBATCH -p fat6326
#SBATCH --job-name=motzkin
##SBATCH --output=logs/N%j.out
##SBATCH --error=logs/N%j.err
##SBATCH --time=01:00:00
#SBATCH --exclusive
## SBATCH -c 4


# Define the number of processes
NUM_PROCS=30

# # Check if command-line arguments are provided
# if [ "$#" -lt 3 ]; then
#     echo "Usage: ./run.sh L T Tthermal"
#     echo "Example: ./run.sh 10000 100000 10000"
#     exit 1
# fi

L=$3
# T=500000000
# Tthermal=1000000000
T=$4
Tthermal=$5
# T=20000
# Tthermal=10000
taskid=$1

# export JULIA_DEPOT_PATH="~/.julia_old"
# srun julia main.jl 
S=$2
echo $taskid $S $L $T $Tthermal
# 把错误输出到同一个文件 (Redirecting error to the same file)
# Run the Julia script with mpiexec, redirecting both stdout and stderr
mpiexec -n $NUM_PROCS julia code/main.jl $L $T $Tthermal $taskid $S all > logs/L${L}S${S}T${T}Tthm${Tthermal}_${taskid} 2>&1  &
wait